#!/bin/bash

CLEAR_FOLDER=$1;
INFECTED_FOLDER=$2;

TEMP_DIR='.tmp';
TEMP_FILE="$TEMP_DIR/newfiles-relative-path";
OUTPUT_FILE="$TEMP_DIR/newfiles";

rm -f $TEMP_FILE;
rm -f $OUTPUT_FILE;
mkdir -p $TEMP_DIR;

/usr/bin/diff -qr --ignore-all-space $CLEAR_FOLDER $INFECTED_FOLDER | grep "Only in $INFECTED_FOLDER" | sed 's/Only in //g' | sed 's/: /\//g' | grep "\.php" > $TEMP_FILE

./file-selector $TEMP_FILE $OUTPUT_FILE;

rm -f $TEMP_FILE;
